[package]
name = "vaultmind"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
vaultmind = "0x90f9d866ff0c03311134107d931d41dd08223234051c76984ef332862903ae46"